export const ICON_SIZE = {
  DEFAULT: "size-18",
  SIZE12: "size-12",
  SIZE14: "size-14",
  SIZE16: "size-16",
  SIZE18: "size-18",
  SIZE20: "size-20",
  SIZE24: "size-24",
  SIZE32: "size-32",
  SIZE40: "size-40",
  SIZE48: "size-48",
  SIZE64: "size-64",
  SIZE96: "size-96",
  SIZE128: "size-128"
};

export const ICON_NAME = {
  PLUS: "plus",
  CROSS: "cross",
  DELETE: "trash",
  LOADING: "loading",
  EYE: "eye",
  EYE_SLASH: "eye-slash",
  OMIT: "omit",
  DOWN: "down",
  UP: "up",
  PAPER_PLANE: "PaperPlane",
  WARNING: "warning-circle-fill",
  ERROR: "close-circle-fill",
  SUCCESS: "check-circle-fill",
  INFO: "info-circle-fill",
  ABOUT: "info-circle",
  MENU: "menu",
  EDIT: "edit-square",
  DASHBOARD: "dashboard",
  SETTING: "setting1",
  INTERNET: "network",
  COPY: "copy",
  DNS: "dns",
  FOLDER: "folder-open-fill",
  QRCODE: "qrcode",
  CLOSE: "close",
  INFO_VARIANT: "information-variant"
};
